spring.application.name=spring-reactive-mongodb
spring.mongodb.uri=mongodb://admin:password@127.0.0.1:27017/reactive_db?authSource=admin
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9000/oauth2/jwks
server.port=8081